services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/competition_app
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - backend
    environment:
      - BACKEND_API_URL=http://localhost:8000


  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=competition_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 