services:
  shed-tournament-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@shed-tournament-db:5432/competition_app
    depends_on:
      - shed-tournament-db
    volumes:
      - ./backend:/app
      - /app/venv

  shed-tournament-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "81:80"
    depends_on:
      - shed-tournament-api
    environment:
      - BACKEND_API_URL=http://localhost:8000


  shed-tournament-db:
    image: postgres:15
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=competition_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 

networks:
  app-network:
    driver: bridge


