services:
  shed-tournament-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network
      - lsio
    ports:
      - "4322:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@shed-tournament-db:5432/competition_app
      - APP_PASSWORD=your-secure-password-here
      - AUTH_SECRET_KEY=your-secret-key-here
    depends_on:
      - shed-tournament-db
    volumes:
      - ./backend:/app

  shed-tournament-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PUBLIC_URL=/shed
        - REACT_APP_API_URL=https://slkmn.k.vu/shedapi
    restart: unless-stopped
    networks:
      - app-network
      - lsio
    ports:
      - "4321:80"
    depends_on:
      - shed-tournament-api
    environment:
      - BACKEND_API_URL=https://slkmn.k.vu/shedapi
      - PUBLIC_URL=/shed
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4321/shed"]
      interval: 30s
      timeout: 10s
      retries: 3


  shed-tournament-db:
    image: postgres:15
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=competition_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 

networks:
  app-network:
    driver: bridge
  lsio:
    name: lsio

